apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-web
  template:
    metadata:
      labels:
        app: ecom-web
    spec:
      containers:
      - name: ecom-web
        image: ariyonaty/ecom-web:v2
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-info
              key: hostname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-info
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-info
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-info
              key: dbname
        - name: FEATURE_DARK_MODE
          valueFrom:
            configMapKeyRef:
              name: feature-toggle-config
              key: FEATURE_DARK_MODE
        livenessProbe:
          httpGet:
            path: /index.php
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /index.php
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
